AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ContactPostHandlerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ContactPostHandler
      Handler: contact_handler.lambda_handler
      Runtime: python3.13
      Code:
        # S3Bucket: contact-us-src-867344438083
        S3Bucket: !Sub contact-us-src-${AWS::AccountId}
        S3Key: lambda/contact_handler.zip
      # Role: arn:aws:iam::867344438083:role/lambda-excution-ContactPostHandler-role
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda-excution-ContactPostHandler-role
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          DYNAMODB_TABLE: contact-inquiries
      Tags:
        - Key: aws-exam-resource
          Value: true
        - Key: project
          Value: exam-00704
