version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.13
  build:
    commands:
      # 1. CloudFormationテンプレートをアーティファクトディレクトリにコピー
      - mkdir -p artifacts/templates
      - cp -p cfn/template.yaml artifacts/templates/

      # 2. LambdaコードをZip化
      - mkdir -p artifacts/lambda
      - zip -j artifacts/lambda/contact_handler.zip cfn/lambda/src/*

      # 3. 動的なS3キーを生成（タイムスタンプを利用）
      - export S3_KEY=lambda/contact_handler-$(date +%s).zip

      # 4. S3キーを記録して次のステージに渡す
      - echo $S3_KEY > artifacts/s3-key.txt
      - cat artifacts/s3-key.txt

    finaly:
      # 1. 静的ファイルをS3にアップロード
      - aws s3 cp cfn/statics/ s3://$STATICS_BUCKET_NAME/ --recursive

      # 2. Lambdaコード（Zip化されたファイル）をS3にアップロード
      - aws s3 cp artifacts/lambda/contact_handler.zip s3://$SRC_BUCKET_NAME/$S3_KEY

artifacts:
  files:
    - artifacts/template.yaml
    - artifacts/s3-key.txt
    # test
