AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # Lambda関数
  ContactPostHandlerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ContactPostHandler
      Handler: contact_handler.lambda_handler
      Runtime: python3.13
      Code:
        S3Bucket: !Sub contact-us-src-${AWS::AccountId}
        S3Key: lambda/contact_handler.zip
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda-excution-ContactPostHandler-role
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          DYNAMODB_TABLE: contact-inquiries
      Tags:
        - Key: aws-exam-resource
          Value: true
        - Key: project
          Value: exam-00704

  # HTTP API Gateway
  ContactHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: ContactHttpApi
      ProtocolType: HTTP
      Tags:
        project: exam-00704
        environment: production

  # Lambdaインテグレーション
  ContactHttpApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ContactHttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt ContactPostHandlerLambda.Arn
      PayloadFormatVersion: "2.0"

  # HTTP API Route (/contact)
  ContactHttpApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ContactHttpApi
      RouteKey: POST /contact
      AuthorizationType: NONE
      Target: !Sub integrations/${ContactHttpApiIntegration}

  # HTTP API Deployment
  ContactHttpApiDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ContactHttpApiRoute
      - ContactHttpApiIntegration
  Properties:
      ApiId: !Ref ContactHttpApi

  # HTTP API Stage (prod)
  ContactHttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ContactHttpApi
      StageName: "$default"
      DeploymentId: !Ref ContactHttpApiDeployment
      AutoDeploy: true
      AccessLogSettings:
        DestinationArn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/api-gateway/ContactHttpApi/prod
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","caller":"$context.identity.caller","user":"$context.identity.user","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath","status":"$context.status","protocol":"$context.protocol","responseLength":"$context.responseLength"}'
